#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="phreebooksR37RC1.zip"
URL="http://downloads.sourceforge.net/project/phreebooks/Current%20Stable/$VERSION"

dl $URL /usr/local/src

