#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="PhreedomR35RC3.zip"
URL="http://sourceforge.net/projects/phreedom/files/Current%20Stable/$VERSION"

dl $URL /usr/local/src

