#!/bin/sh -ex

DB_NAME=phreedom
DB_USER=phreedom
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/phreedom

# unpack and set permissions
unzip $SRC/Phreedom*.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/Phreedom $WEBROOT
rm $SRC/Phreedom*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/includes
chown -R www-data:www-data $WEBROOT/my_files

# tweak php settings
CONF=/etc/php5/apache2/php.ini
sed -i "s|;upload_tmp_dir.*|upload_tmp_dir = /tmp|" $CONF

# configure apache
a2dissite default
a2ensite phreedom
a2enmod rewrite

