#!/bin/bash -e
# regenerate phreedom mysql password

. /etc/default/inithooks

CONF=/var/www/phreedom/my_files/phreedom/config.php
PASSWORD=$(mcookie)
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD','$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=phreedom --pass="$PASSWORD"

