#!/bin/bash -e
# regenerate phreebooks mysql password

. /etc/default/inithooks

CONF=/var/www/phreebooks/my_files/phreebooks/config.php
PASSWORD=$(mcookie)
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD','$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=phreebooks --pass="$PASSWORD"

